### ISSUE TITLE
EBF: Clean error during doc upload

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#259] opened 2015-01-29 22:36 UTC
Reported by user. Jake will get details from user and Dave will get details from logs and report back here.

**Comment by daguar** [comment] 2015-01-29 22:38
I have confirmed the error in production logs, see below:

![screen shot 2015-01-29 at 2 38 05 pm](https://cloud.githubusercontent.com/assets/994938/5967679/887e745a-a7c4-11e4-90ca-f0d129f53a6b.png)

**Comment by daguar** [comment] 2015-01-29 22:41
My suspicion on what's happening is that the filename of the PDF file they uploaded had a character in it that our code doesn't like currently (I believe a `&` and/or a `#`). I will investigate further and try to replicate. My process will be:

- Confirm dev has same code base as production
- Manually use the doc upload on dev with a PDF that DOES NOT have special characters to confirm that is functioning
- Name a PDF file after the name I see, and try uploading _that_ file on dev

Will report back here when I know more.

**Comment by daguar** [comment] 2015-01-29 22:50
Turned above into a checklist; have confirmed dev and production are both on master.

**Comment by daguar** [comment] 2015-01-29 22:55
Added issue for setting up alerts to catch things like these happening so that users don't have to report to us.

**Comment by daguar** [comment] 2015-01-29 23:23
Have replicated the error using the above-specified approach — have confirmed that it was due to special characters being in the name.

Working on a fix now.

**Comment by migurski** [comment] 2015-01-29 23:27
Generally don’t trust user input on filenames.

**Comment by daguar** [comment] 2015-01-29 23:27
To explain the error a bit more — we clean out spaces from the names of files being uploaded, but we did _not_ clean out any special (ie, non-alphanumeric) characters, leading to a filesystem read error on Ubuntu (Heroku's OS).

The relevant code is:

```ruby
    def initialize(doc_param)
      if doc_param.count > 0
        raw_doc = doc_param.first[1]
        raw_doc_path = raw_doc[:tempfile].path
        filename = raw_doc[:filename]
        new_file_path = raw_doc_path + filename
        new_file_path_no_spaces = new_file_path.gsub(" ", "")
        system("cp #{raw_doc_path} #{new_file_path_no_spaces}")
        @original_file_path = new_file_path_no_spaces
      end
    end
```

**Comment by daguar** [comment] 2015-01-29 23:29
:+1: @migurski, agreed. We (insufficiently) sanitize, but I may create new names entirely.

**Comment by migurski** [comment] 2015-01-29 23:36
I’d do that for sure! Make a name based on your internal IDs; I doubt the name of the PDF is important for the app.

**Comment by daguar** [comment] 2015-01-29 23:39
The tricky part is that sometimes they are somewhat useful since we're submitting a generic doc over email to an eligibility worker — case in point, this error came from `ID&SS#.pdf`, which is somewhat helpful, though not _that_ helpful. So I think that was the impetus, but we'll handle this.

**Comment by lippytak** [comment] 2015-01-29 23:47
Offering some edits to @migurski wisdom above:
- "Generally don’t trust user input on filenames."
- "G̶e̶n̶e̶r̶a̶l̶l̶y̶ don’t trust user input on filenames."
- "G̶e̶n̶e̶r̶a̶l̶l̶y̶ don’t trust user input o̶n̶ ̶f̶i̶l̶e̶n̶a̶m̶e̶s̶."
- "G̶e̶n̶e̶r̶a̶l̶l̶y̶ don’t trust users i̶n̶p̶u̶t̶ ̶o̶n̶ ̶f̶i̶l̶e̶n̶a̶m̶e̶s̶."

Ahh, that's better.

> Love users, don't trust them.
@lippytak, 2015

**Comment by lippytak** [comment] 2015-01-30 00:48
Just spoke to Jackie. Notes on the bug:
- Lisa (Jackie's one staffer who does benefit enrollment stuff full time?!) using Desktop Chrome (how'd they get the img on the comp?)
- Error before she could upload a single doc
- Tried 2 times
- Submitted app without doc then emailed verifications to food@sfgov.org (see https://github.com/codeforamerica/clean/issues/261)

Other:
- They've done a few cases successfully so far (I DIDN'T EVEN KNOW THAT!?)
- Confirmation - specifically asked to be able to print the application for their records (https://github.com/codeforamerica/clean/issues/126)
- Want timeline AKA 'expect a call within XYZ'

@daguar, ship the fix at your convenience, ping me to update the user + Liliana and then we can safely close our first Clean Emergency Bug Fix (EBF). Congrats!

**Comment by daguar** [comment] 2015-01-30 02:23
My commit message on the code fix ( https://github.com/codeforamerica/clean/commit/b6490478da730d704e0fca5836c18d763286de40 ) for this closed this issue, but confirming that this is fixed and live on all servers.

Re-opening for the final notification to the users — @lippytak let me know if you need any more info, and please close this when you've notified the users.

**Comment by lippytak** [comment] 2015-01-30 07:57
Done. Great job on this all around.

**Closed** 2015-01-30 07:56 UTC

**Comment by alanjosephwilliams** [comment] 2015-01-30 17:00
big :+1:
